### ISSUE TITLE
Failed to add exclude rules

### ISSUE THREAD

**Issue by langlangsAgo** [cernekee/ics-openconnect#43] opened 2018-12-06 03:52 UTC
I want to add some ip.splitExcludes to vpn.Firstly I add the default include rute"0.0.0.0/0". 
The result is that the network is all through vpn,so how can I add the splitExcludes into vpn

**Comment by dawei101** [comment] 2019-06-03 14:03
any support?

**Comment by dlenski** [comment] 2019-06-05 03:38
Duplicate of #10.

**Closed by dlenski** 2019-06-05 03:38 UTC
